### ISSUE TITLE
support DI Frameworks through JSR-330 integration

### ISSUE THREAD

**Issue by lesaint** [lesaint/damapping#32]
current support for DI Framework integration is limited to Spring, the `@Component` annotation and property injection with `@Resource`

the idea here is to implement DI framework integration via the [JSR-330 specification](https://jcp.org/en/jsr/detail?id=330) so that we can integrate with all the DI frameworks supporting this standard.
### create `@Injectable`

We need to add a new annotation `@Injectable` which will identify MapperImpl class which must integrate with a JSR-330 compliant dependency injection framework.

We are using a separate annotation instead of a member on `@Mapper` to leave open adding specific member to `@Injectable` customize CDI integration.
### replace `@Resource`

`@Resource` annotation on property can be replaced with annotation `@Inject` from JSR-330.
### use constuctor injection

Since I don't like property injection (leaves door open for mutation on injected bean because we can not use `final` on property), we shall replace property injection with constructor injection during this dev.
### drop `@Component`

Spring supports using the JSR-330 annotation `@Named` on class as a replacement of `@Component`.

Unfortunatly, this is not standard as described in `@Qualifier` annnotation's javadoc:

```
While this specification covers applying qualifiers to fields and parameters only, some injector configurations might use qualifier annotations in other places (on methods or classes for example).
```

Conclusion, we won't generate MapperImpl classes with `@Named` by default.

The single impact is that Spring package scan functionnality can not be used by default anymore.
### implementation steps
- [X] support to JSR-330 only for mapper without @MapperFactory
  - [X] use specific integration test (fork mapper-component ?)
  - [X] support references to generate code by adding @Inject on constructor
- [X] raise compile error and do not process type with @Injectable if @Named or @Inject annotations are not in the classpath
- [X] add compile time check that @Injectable is present only on type with @Mapper too (DAMapping annotation processor must register @Injectable too, perform a check at beginning of each round: retrieve all types with @Injectable and verify each of them have @Mapper too)
- [X] add unit test for mapper using mapper using mapper... (should work out-of-the-box)
- [X] remove support for InstantiationType.SPRING_COMPONENT
  - [X] rewrite use-mapper integration test with @Injectable
- [x] add integration-test of @Injectable integration with Dagger
- [X] support JSR-330 with @MapperFactory methods
